### ISSUE TITLE
Using the wrapper for ps7

### ISSUE THREAD

**Issue by Felkin1** [satellogic/nmigen-zynq#1]
How difficult would it be to adjust the layouts file to support the ps7? I'm having trouble even finding information on the ps8. Would love to use this wrapper for use in a PYNQ board.

**Comment by ydnatag** [comment]
It is not difficult. But i recommend to use https://github.com/apertus-open-source-cinema/naps/blob/main/naps/soc/platform/zynq/zynq_soc_platform.py . It is more mature and used in a real opensource project.

If you want to add ps7 support to this project, you need to read ps7.v from yosys or xilinx unisim libraries and translate that to nmigen.

**Comment by AlexYzhov** [comment]
Hi, I've added ps7 support and raised a PR [here](https://github.com/satellogic/nmigen-zynq/pull/5). 

Maybe this can help you

**Comment by akukulanski** [comment]
merged! thanks
